<a href="https://colab.research.google.com/github/girishjalli18/intro-to-ml-on-aws-crsra/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. import numpy
2. create a an np array with python list [1,2,3,4,5]
3. check the shape
4. crate an array with arange function
5. create a np array of zeros shape (3,4)
6. create a np array of ones shape (4,4)
7. craete a np array with full values with 5
8. create a identiy array
9. create a np array with random floats
10. crate a np array with random ints
11. create a np array with values between 10, 60 at linspace of 5
12. crete np array between 10, 60 using arange and step value
13. convert a list into an np.array
14. create a np array of random ints and analyze, shape, dimention, num of elements ( np.shape, np.ndim, np.size)
15. check the data type of the values inthe np array using dtypes
16. arthematic operations on np arrays
  - create two arrays the perform add, subtraction, multiplicaiton, and division, use both +,-,*,/ and np.add, np.subtract, np.multiplication, np.division check the exact functions
17. reshape a given array
18. get the transpose of np array, np.transpose, np.T


In [1]:
import numpy as np

In [2]:
# 2. create a an np array with python list [1,2,3,4,5]
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [4]:
#  3. check the shape
a.shape

(5,)

In [5]:
a.size

5

In [7]:
# 4. crate an array with arange function
a = np.arange(10, 30, 5)
print(a)

[10 15 20 25]


In [9]:
# 5. create a np array of zeros shape (3,4)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# 6. create a np array of ones shape (4,4)
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#  7. craete a np array with full values with 5
np.full((4,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [12]:
# 8.create a identiy array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# 9.create a np array with random floats
np.random.random((3,2)) * 100

array([[51.66124522,  0.81980428],
       [53.34846666, 77.16481169],
       [66.0850239 , 27.85359653]])

In [19]:
# 10.crate a np array with random ints
np.random.randint(1, 100, size=(3,3))

array([[74, 27, 30],
       [88, 70, 24],
       [85,  1, 72]])

In [22]:
# 11.create a np array with values between 10, 60 at linspace of 5
np.linspace(10, 60, 5)

array([10. , 22.5, 35. , 47.5, 60. ])

In [23]:
np.arange(10,60, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [24]:
# 12. crete np array between 10, 60 using arange and step value
np.arange(10,60, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [25]:
# 13.convert a list into an np.array
list1 = [1,2,4,5.6]
l1 = np.array(list1)
type(l1)

numpy.ndarray

In [35]:
# 14.create a np array of random ints and analyze, shape, dimention, num of elements ( np.shape, np.ndim, np.size)
a = np.random.randint(10,40, size=(3,3))
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3, 3)
2
9
int64


In [33]:
#15 check the data type of the values inthe np array using dtypes
a.dtype

dtype('int64')

In [36]:
# 16.arthematic operations on np arrays
# create two arrays the perform add, subtraction, multiplicaiton, and division, use both +,-,*,/ and np.add, np.subtract, np.multiplication, np.division check the exact functions
a = np.random.randint(10, 30, size=(2,3))
b = np.random.randint(10, 30, size=(2,3))
# add two np arrays
print(a + b)
print(a-b)
print(a*b)
print(a/b)

# with np funcitons
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))

[[32 32 39]
 [42 43 45]]
[[12  6  9]
 [14 -7  3]]
[[220 247 360]
 [392 450 504]]
[[2.2        1.46153846 1.6       ]
 [2.         0.72       1.14285714]]
[[32 32 39]
 [42 43 45]]
[[12  6  9]
 [14 -7  3]]
[[220 247 360]
 [392 450 504]]
[[2.2        1.46153846 1.6       ]
 [2.         0.72       1.14285714]]
[[      26559922791424    42052983462257059  6795192965888212992]
 [-2408320907152982016  6890854633187573760 -9223372036854775808]]
[[ 2  6  9]
 [ 0 18  3]]


In [39]:
# 17. reshape a given array

a =np.array([[1,2,3,4], [4,5,6,7]])
print(a)
a.reshape(4,2)

[[1 2 3 4]
 [4 5 6 7]]


array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [42]:
# 18.get the transpose of np array, np.transpose, np.T
a = np.random.randint(10, 30, size=(4,2))
print(a)
# transpose
print(a.transpose())
# transpose
print(a.T)


[[23 25]
 [22 17]
 [23 20]
 [27 18]]
[[23 22 23 27]
 [25 17 20 18]]
[[23 22 23 27]
 [25 17 20 18]]


In [8]:
a = np.linspace(10, 30, 5)
print(a)

[10. 15. 20. 25. 30.]
